#Configuration for mattermost
[mattermost]

    #Email and password for matterrmost, user may be system-administrator
    email = "qwerty@gmail.com"
    password = "qwerty"

    #Address and port which will used in https request to mattermost
    address = "192.168.88.62"
    port = "8065"

#Configuration for portainer
[portainer]

    #Login and password for portainer, user may be admin
    login = "admin"
    password = "adminadmin"

    #Address and port which will used in https request to portainer
    address = "localhost"
    port = "9000"

    #Time in seconds wich mean how often pragram will check fallen containers
    check_interval = "3"

#Configuration for LevelDB
[level]

    #Path to level db
    path = "storage/storage"

#Configuration for server
[api]
    #Port wich we will listen in rest
    port = "1119"