#Configuration for mattermost
[mattermost]

    #Email and password for matterrmost, user may be system-administrator
    email = "qwerty@gmail.com"
    password = "qwerty"

    #Address and port which will used in https request to mattermost
    address = "localhost"
    port = "8065"

#Configuration for portainer
[portainer]

    #Login and password for portainer, user may be admin
    login = "admin"
    password = "adminadmin"

    #Address and port which will used in https request to portainer
    address = "localhost"
    port = "1122"

    #Time in seconds wich mean how often pragram will check fallen containers
    check_interval = "3"

    #Amount of logs which will send to mattermost
    logs_amount = "100"

#Configuration for LevelDB
[level]

    #Path to level db
    path = "$HOME/.portaineerPlugin/storage/"

#Configuration for server
[api]
    #Port wich we will listen in rest
    port = "1119"
    #Key which will sing all jwt token
    jwt_signing_key = "das3f12A32f32a33efA3E32F32f3e2FW32f32e"

[log]
    #panic
    #fatal
    #error
    #warn
    #info
    #debug
    #trace
    level = "trace"